include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_final_fields: true
    use_key_in_widget_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    prefer_is_empty: true
    unnecessary_this: true
    prefer_typing_uninitialized_variables: true
    avoid_function_literals_in_foreach_calls: true
    prefer_collection_literals: true