// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Web exists so `flutter run -d chrome` is a usable preview of screens
  /// that need a signed-in uid — without it Firebase fails to initialise in a
  /// browser, the account layer is null, and the opening silently skips its
  /// last step. Not a shipping target.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm-ImCshj9k_EBXx86y-mhdTyrkBh7-ao',
    appId: '1:592310164564:web:3668f5dc9307f2cc5a61c1',
    messagingSenderId: '592310164564',
    projectId: 'mojilearner-38de1',
    authDomain: 'mojilearner-38de1.firebaseapp.com',
    storageBucket: 'mojilearner-38de1.firebasestorage.app',
    measurementId: 'G-HG0LB0H1PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSU-UdxkSTrzicZLEkordZ7aU3cM4m3AE',
    appId: '1:592310164564:android:b41de98e4902fed25a61c1',
    messagingSenderId: '592310164564',
    projectId: 'mojilearner-38de1',
    storageBucket: 'mojilearner-38de1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC53OVaZhtZrBGctbhZHf7x87-hMp8FJf0',
    appId: '1:592310164564:ios:c13fefaa2109f6a45a61c1',
    messagingSenderId: '592310164564',
    projectId: 'mojilearner-38de1',
    storageBucket: 'mojilearner-38de1.firebasestorage.app',
    iosBundleId: 'com.mimikin.app',
  );
}
