$ErrorActionPreference = "Stop"
$root = "lib/l10n"
$english = @{
  youLabel = "You"
  mojiSleepReconnect = "Zzz... Moji is dozing while the language link reconnects. Try again soon."
  mojiSleepNight = "Shhh... Moji is sleeping. Tap Moji to wake up."
  mojiSleepHintReconnect = "MOJI IS DOZING... LANGUAGE LINK RECONNECTING"
  mojiSleepHintNight = "MOJI IS SLEEPING... TAP TO WAKE"
  mojiWakeSuccess = "Yawn... Moji is awake now. Let's practice!"
  mojiSleepReasonReconnect = "Moji is dozing while the language link reconnects."
  mojiSleepReasonNight = "Moji is sleeping. Tap to wake up."
}
$translations = @{
  en = $english
  es = @{ youLabel='Tú'; mojiSleepReconnect='Zzz... Moji está dormitando mientras se reconecta el enlace de idioma. Inténtalo de nuevo pronto.'; mojiSleepNight='Shhh... Moji está dormido. Toca a Moji para despertarlo.'; mojiSleepHintReconnect='MOJI ESTÁ DORMITANDO... RECONECTANDO ENLACE DE IDIOMA'; mojiSleepHintNight='MOJI ESTÁ DORMIDO... TOCA PARA DESPERTAR'; mojiWakeSuccess='Bostezo... Moji ya está despierto! Practiquemos!'; mojiSleepReasonReconnect='Moji está dormitando mientras se reconecta el enlace de idioma.'; mojiSleepReasonNight='Moji está dormido. Toca para despertarlo.' }
  fr = @{ youLabel='Toi'; mojiSleepReconnect='Zzz... Moji somnole pendant que la connexion linguistique se rétablit. Réessaie bientôt.'; mojiSleepNight='Chut... Moji dort. Appuie sur Moji pour le réveiller.'; mojiSleepHintReconnect='MOJI SOMNOLE... RECONNEXION DU LIEN LINGUISTIQUE'; mojiSleepHintNight='MOJI DORT... APPUIE POUR RÉVEILLER'; mojiWakeSuccess='Bâillement... Moji est réveillé maintenant ! On sentraîne !'; mojiSleepReasonReconnect='Moji somnole pendant que la connexion linguistique se rétablit.'; mojiSleepReasonNight='Moji dort. Appuie pour le réveiller.' }
  de = @{ youLabel='Du'; mojiSleepReconnect='Zzz... Moji döst, während die Sprachverbindung wiederhergestellt wird. Versuch es bald erneut.'; mojiSleepNight='Psst... Moji schläft. Tippe auf Moji, um ihn zu wecken.'; mojiSleepHintReconnect='MOJI DÖST... SPRACHVERBINDUNG WIRD WIEDERHERGESTELLT'; mojiSleepHintNight='MOJI SCHLÄFT... ZUM WECKEN TIPPEN'; mojiWakeSuccess='Gähn... Moji ist jetzt wach! Lass uns üben!'; mojiSleepReasonReconnect='Moji döst, während die Sprachverbindung wiederhergestellt wird.'; mojiSleepReasonNight='Moji schläft. Zum Wecken tippen.' }
  it = @{ youLabel='Tu'; mojiSleepReconnect='Zzz... Moji sonnecchia mentre il collegamento linguistico si riconnette. Riprova tra poco.'; mojiSleepNight='Shhh... Moji sta dormendo. Tocca Moji per svegliarlo.'; mojiSleepHintReconnect='MOJI SONNECCHIA... COLLEGAMENTO LINGUISTICO IN RICONNESSIONE'; mojiSleepHintNight='MOJI DORME... TOCCA PER SVEGLIARE'; mojiWakeSuccess='Sbadiglio... Moji ora è sveglio! Facciamo pratica!'; mojiSleepReasonReconnect='Moji sonnecchia mentre il collegamento linguistico si riconnette.'; mojiSleepReasonNight='Moji sta dormendo. Tocca per svegliarlo.' }
  pt = @{ youLabel='Você'; mojiSleepReconnect='Zzz... O Moji está cochilando enquanto o link de idioma se reconecta. Tente novamente em breve.'; mojiSleepNight='Shhh... O Moji está dormindo. Toque no Moji para acordá-lo.'; mojiSleepHintReconnect='MOJI COCHILANDO... RECONECTANDO LINK DE IDIOMA'; mojiSleepHintNight='MOJI DORMINDO... TOQUE PARA ACORDAR'; mojiWakeSuccess='Bocejo... O Moji acordou! Vamos praticar!'; mojiSleepReasonReconnect='O Moji está cochilando enquanto o link de idioma se reconecta.'; mojiSleepReasonNight='O Moji está dormindo. Toque para acordar.' }
  ru = @{ youLabel='Ты'; mojiSleepReconnect='Zzz... Модзи дремлет, пока языковая связь переподключается. Попробуй снова чуть позже.'; mojiSleepNight='Тсс... Модзи спит. Нажми на Модзи, чтобы разбудить его.'; mojiSleepHintReconnect='MOJI ДРЕМЛЕТ... ЯЗЫКОВАЯ СВЯЗЬ ПЕРЕПОДКЛЮЧАЕТСЯ'; mojiSleepHintNight='MOJI СПИТ... НАЖМИ, ЧТОБЫ РАЗБУДИТЬ'; mojiWakeSuccess='Зевок... Модзи проснулся! Давай практиковаться!'; mojiSleepReasonReconnect='Модзи дремлет, пока языковая связь переподключается.'; mojiSleepReasonNight='Модзи спит. Нажми, чтобы разбудить.' }
  ja = @{ youLabel='あなた'; mojiSleepReconnect='Zzz... 言語リンクの再接続中、Mojiはうとうとしています。しばらくしてからもう一度お試しください。'; mojiSleepNight='シーッ... Mojiは眠っています。Mojiをタップして起こしてください。'; mojiSleepHintReconnect='MOJI はうとうと中... 言語リンクを再接続しています'; mojiSleepHintNight='MOJI はおやすみ中... タップして起こす'; mojiWakeSuccess='ふぁぁ... Mojiは起きました！練習しよう！'; mojiSleepReasonReconnect='言語リンクの再接続中、Mojiはうとうとしています。'; mojiSleepReasonNight='Mojiは眠っています。タップして起こしてください。' }
  ko = @{ youLabel='당신'; mojiSleepReconnect='Zzz... 언어 연결을 다시 연결하는 동안 Moji가 꾸벅꾸벅 졸고 있어요. 잠시 후 다시 시도해 주세요.'; mojiSleepNight='쉿... Moji가 자고 있어요. Moji를 탭해서 깨워 주세요.'; mojiSleepHintReconnect='MOJI 졸고 있음... 언어 연결 재연결 중'; mojiSleepHintNight='MOJI 수면 중... 탭해서 깨우기'; mojiWakeSuccess='하암... Moji가 이제 깼어요! 연습해요!'; mojiSleepReasonReconnect='언어 연결을 다시 연결하는 동안 Moji가 꾸벅꾸벅 졸고 있어요.'; mojiSleepReasonNight='Moji가 자고 있어요. 탭해서 깨워 주세요.' }
  zh = @{ youLabel='你'; mojiSleepReconnect='Zzz... Moji 正在打盹，语言连接正在重新连接。请稍后再试。'; mojiSleepNight='嘘... Moji 在睡觉。点击 Moji 把它叫醒。'; mojiSleepHintReconnect='MOJI 正在打盹... 语言连接正在重连'; mojiSleepHintNight='MOJI 正在睡觉... 点击唤醒'; mojiWakeSuccess='哈欠... Moji 现在醒啦！我们来练习吧！'; mojiSleepReasonReconnect='Moji 正在打盹，语言连接正在重新连接。'; mojiSleepReasonNight='Moji 在睡觉。点击唤醒。' }
  ar = @{ youLabel='أنت'; mojiSleepReconnect='ززز... موجي يغفو بينما يعيد رابط اللغة الاتصال. حاول مرة أخرى قريبا.'; mojiSleepNight='ششش... موجي نائم. اضغط على موجي لإيقاظه.'; mojiSleepHintReconnect='موجي يغفو... جار إعادة اتصال رابط اللغة'; mojiSleepHintNight='موجي نائم... اضغط للإيقاظ'; mojiWakeSuccess='تثاؤب... موجي مستيقظ الآن! هيا نتدرب!'; mojiSleepReasonReconnect='موجي يغفو بينما يعيد رابط اللغة الاتصال.'; mojiSleepReasonNight='موجي نائم. اضغط للإيقاظ.' }
  hi = @{ youLabel='आप'; mojiSleepReconnect='जज... मज ऊघ रह ह जबक भष लक फर स जड रह ह कपय थड दर म फर कशश कर'; mojiSleepNight='शश... मज स रह ह मज क जगन क लए टप कर'; mojiSleepHintReconnect='MOJI ऊघ रह ह... भष लक फर स जड रह ह'; mojiSleepHintNight='MOJI स रह ह... जगन क लए टप कर'; mojiWakeSuccess='जभई... मज अब जग गय ह! चल अभयस कर!'; mojiSleepReasonReconnect='मज ऊघ रह ह जबक भष लक फर स जड रह ह'; mojiSleepReasonNight='मज स रह ह जगन क लए टप कर' }
  tr = @{ youLabel='Sen'; mojiSleepReconnect='Zzz... Dil bağlantısı yeniden bağlanırken Moji kestiriyor. Kısa süre sonra tekrar dene.'; mojiSleepNight='Şşş... Moji uyuyor. Uyandırmak için Moji''ye dokun.'; mojiSleepHintReconnect='MOJI KESTİRİYOR... DİL BAĞLANTISI YENİDEN BAĞLANIYOR'; mojiSleepHintNight='MOJI UYUYOR... UYANDIRMAK İÇİN DOKUN'; mojiWakeSuccess='Esneme... Moji şimdi uyanık! Hadi pratik yapalım!'; mojiSleepReasonReconnect='Dil bağlantısı yeniden bağlanırken Moji kestiriyor.'; mojiSleepReasonNight='Moji uyuyor. Uyandırmak için dokun.' }
  nl = @{ youLabel='Jij'; mojiSleepReconnect='Zzz... Moji dut terwijl de taalkoppeling opnieuw verbinding maakt. Probeer het zo opnieuw.'; mojiSleepNight='Ssst... Moji slaapt. Tik op Moji om hem wakker te maken.'; mojiSleepHintReconnect='MOJI DUT... TAALKOPPELING MAAKT OPNIEUW VERBINDING'; mojiSleepHintNight='MOJI SLAAPT... TIK OM WAKKER TE MAKEN'; mojiWakeSuccess='Gaap... Moji is nu wakker! Laten we oefenen!'; mojiSleepReasonReconnect='Moji dut terwijl de taalkoppeling opnieuw verbinding maakt.'; mojiSleepReasonNight='Moji slaapt. Tik om wakker te maken.' }
  sv = @{ youLabel='Du'; mojiSleepReconnect='Zzz... Moji slumrar medan språklänken återansluts. Försök igen snart.'; mojiSleepNight='Shhh... Moji sover. Tryck på Moji för att väcka honom.'; mojiSleepHintReconnect='MOJI SLUMRAR... SPRÅKLÄNKEN ÅTERANSLUTS'; mojiSleepHintNight='MOJI SOVER... TRYCK FÖR ATT VÄCKA'; mojiWakeSuccess='Gäsp... Moji är vaken nu! Nu övar vi!'; mojiSleepReasonReconnect='Moji slumrar medan språklänken återansluts.'; mojiSleepReasonNight='Moji sover. Tryck för att väcka.' }
  pl = @{ youLabel='Ty'; mojiSleepReconnect='Zzz... Moji drzemi, podczas gdy połączenie językowe łączy się ponownie. Spróbuj ponownie za chwilę.'; mojiSleepNight='Ciii... Moji śpi. Dotknij Mojiego, aby go obudzić.'; mojiSleepHintReconnect='MOJI DRZEMIE... POŁĄCZENIE JĘZYKOWE ŁĄCZY SIĘ PONOWNIE'; mojiSleepHintNight='MOJI ŚPI... DOTKNIJ, ABY OBUDZIĆ'; mojiWakeSuccess='Ziew... Moji już nie śpi! Poćwiczmy!'; mojiSleepReasonReconnect='Moji drzemi, podczas gdy połączenie językowe łączy się ponownie.'; mojiSleepReasonNight='Moji śpi. Dotknij, aby obudzić.' }
  id = @{ youLabel='Kamu'; mojiSleepReconnect='Zzz... Moji sedang mengantuk saat tautan bahasa tersambung kembali. Coba lagi sebentar lagi.'; mojiSleepNight='Sst... Moji sedang tidur. Ketuk Moji untuk membangunkannya.'; mojiSleepHintReconnect='MOJI MENGANTUK... TAUTAN BAHASA TERSAMBUNG KEMBALI'; mojiSleepHintNight='MOJI TIDUR... KETUK UNTUK MEMBANGUNKAN'; mojiWakeSuccess='Huaa... Moji sudah bangun! Ayo berlatih!'; mojiSleepReasonReconnect='Moji sedang mengantuk saat tautan bahasa tersambung kembali.'; mojiSleepReasonNight='Moji sedang tidur. Ketuk untuk membangunkan.' }
  vi = @{ youLabel='Bạn'; mojiSleepReconnect='Zzz... Moji đang lim dim khi kết nối ngôn ngữ đang kết nối lại. Hãy thử lại sớm nhé.'; mojiSleepNight='Suỵt... Moji đang ngủ. Chạm vào Moji để đánh thức.'; mojiSleepHintReconnect='MOJI ĐANG LIM DIM... KẾT NỐI NGÔN NGỮ ĐANG KẾT NỐI LẠI'; mojiSleepHintNight='MOJI ĐANG NGỦ... CHẠM ĐỂ ĐÁNH THỨC'; mojiWakeSuccess='Ngáp... Moji đã thức rồi! Cùng luyện tập nhé!'; mojiSleepReasonReconnect='Moji đang lim dim khi kết nối ngôn ngữ đang kết nối lại.'; mojiSleepReasonNight='Moji đang ngủ. Chạm để đánh thức.' }
  th = @{ youLabel='คณ'; mojiSleepReconnect='Zzz... โมจกำลงงบอยระหวางทการเชอมตอภาษากำลงเชอมใหม ลองอกครงในอกสกคร'; mojiSleepNight='ชว... โมจกำลงหลบ แตะโมจเพอปลก'; mojiSleepHintReconnect='MOJI กำลงงบ... กำลงเชอมตอภาษากลบมา'; mojiSleepHintNight='MOJI กำลงหลบ... แตะเพอปลก'; mojiWakeSuccess='หาว... ตอนนโมจตนแลว! มาเรมฝกกน!'; mojiSleepReasonReconnect='โมจกำลงงบอยระหวางทการเชอมตอภาษากำลงเชอมใหม'; mojiSleepReasonNight='โมจกำลงหลบ แตะเพอปลก' }
  uk = @{ youLabel='Ти'; mojiSleepReconnect='Zzz... Модзі дрімає, поки мовний звязок перепідключається. Спробуй ще раз незабаром.'; mojiSleepNight='Тсс... Модзі спить. Торкнися Модзі, щоб розбудити.'; mojiSleepHintReconnect='MOJI ДРІМАЄ... МОВНИЙ ЗВЯЗОК ПЕРЕПІДКЛЮЧАЄТЬСЯ'; mojiSleepHintNight='MOJI СПИТЬ... ТОРКНИСЯ, ЩОБ РОЗБУДИТИ'; mojiWakeSuccess='Позіх... Модзі вже прокинувся! Давай практикуватися!'; mojiSleepReasonReconnect='Модзі дрімає, поки мовний звязок перепідключається.'; mojiSleepReasonNight='Модзі спить. Торкнися, щоб розбудити.' }
  ro = @{ youLabel='Tu'; mojiSleepReconnect='Zzz... Moji moțăie în timp ce legătura de limbă se reconectează. Încearcă din nou în curând.'; mojiSleepNight='Șșș... Moji doarme. Atinge-l pe Moji ca să-l trezești.'; mojiSleepHintReconnect='MOJI MOȚĂIE... LEGĂTURA DE LIMBĂ SE RECONECTEAZĂ'; mojiSleepHintNight='MOJI DOARME... ATINGE PENTRU TREZIRE'; mojiWakeSuccess='Căscat... Moji este treaz acum! Să exersăm!'; mojiSleepReasonReconnect='Moji moțăie în timp ce legătura de limbă se reconectează.'; mojiSleepReasonNight='Moji doarme. Atinge pentru trezire.' }
  no = @{ youLabel='Du'; mojiSleepReconnect='Zzz... Moji døser mens språklenken kobles til på nytt. Prøv igjen snart.'; mojiSleepNight='Shhh... Moji sover. Trykk på Moji for å vekke ham.'; mojiSleepHintReconnect='MOJI DØSER... SPRÅKLENKEN KOBLES TIL PÅ NYTT'; mojiSleepHintNight='MOJI SOVER... TRYKK FOR Å VEKKE'; mojiWakeSuccess='Gjesp... Moji er våken nå! La oss øve!'; mojiSleepReasonReconnect='Moji døser mens språklenken kobles til på nytt.'; mojiSleepReasonNight='Moji sover. Trykk for å vekke.' }
  da = @{ youLabel='Dig'; mojiSleepReconnect='Zzz... Moji døser, mens sprogforbindelsen genoprettes. Prøv igen snart.'; mojiSleepNight='Shhh... Moji sover. Tryk på Moji for at vække ham.'; mojiSleepHintReconnect='MOJI DØSER... SPROGFORBINDELSEN GENOPRETTES'; mojiSleepHintNight='MOJI SOVER... TRYK FOR AT VÆKKE'; mojiWakeSuccess='Gaaab... Moji er vågen nu! Lad os øve!'; mojiSleepReasonReconnect='Moji døser, mens sprogforbindelsen genoprettes.'; mojiSleepReasonNight='Moji sover. Tryk for at vække.' }
  fi = @{ youLabel='Sinä'; mojiSleepReconnect='Zzz... Moji torkkuu, kun kieliyhteys muodostetaan uudelleen. Yritä pian uudelleen.'; mojiSleepNight='Shhh... Moji nukkuu. Napauta Mojia herättääksesi hänet.'; mojiSleepHintReconnect='MOJI TORKKUU... KIELIYHTEYS MUODOSTETAAN UUDELLEEN'; mojiSleepHintNight='MOJI NUKKUU... NAPAUTA HERÄTTÄÄKSESI'; mojiWakeSuccess='Haukotus... Moji on nyt hereillä! Harjoitellaan!'; mojiSleepReasonReconnect='Moji torkkuu, kun kieliyhteys muodostetaan uudelleen.'; mojiSleepReasonNight='Moji nukkuu. Napauta herättääksesi.' }
  cs = @{ youLabel='Ty'; mojiSleepReconnect='Zzz... Moji podřimuje, zatímco se znovu připojuje jazykové spojení. Zkus to brzy znovu.'; mojiSleepNight='Pšš... Moji spí. Klepni na Mojiho a probuď ho.'; mojiSleepHintReconnect='MOJI PODŘIMUJE... JAZYKOVÉ SPOJENÍ SE OBNOVUJE'; mojiSleepHintNight='MOJI SPÍ... KLEPNI PRO PROBUZENÍ'; mojiWakeSuccess='Zív... Moji je teď vzhůru! Pojďme trénovat!'; mojiSleepReasonReconnect='Moji podřimuje, zatímco se jazykové spojení obnovuje.'; mojiSleepReasonNight='Moji spí. Klepni pro probuzení.' }
  hu = @{ youLabel='Te'; mojiSleepReconnect='Zzz... Moji szundikál, miközben a nyelvi kapcsolat újracsatlakozik. Próbáld újra hamarosan.'; mojiSleepNight='Psszt... Moji alszik. Koppints Mojira az ébresztéshez.'; mojiSleepHintReconnect='MOJI SZUNDIKÁL... A NYELVI KAPCSOLAT ÚJRACSATLAKOZIK'; mojiSleepHintNight='MOJI ALSZIK... KOPPINTS AZ ÉBRESZTÉSHEZ'; mojiWakeSuccess='Ásítás... Moji most már ébren van! Gyakoroljunk!'; mojiSleepReasonReconnect='Moji szundikál, miközben a nyelvi kapcsolat újracsatlakozik.'; mojiSleepReasonNight='Moji alszik. Koppints az ébresztéshez.' }
  el = @{ youLabel='Εσύ'; mojiSleepReconnect='Ζζζ... Ο Moji νυστάζει όσο επανασυνδέεται ο σύνδεσμος γλώσσας. Δοκίμασε ξανά σύντομα.'; mojiSleepNight='Σσσ... Ο Moji κοιμάται. Πάτησε τον Moji για να ξυπνήσει.'; mojiSleepHintReconnect='Ο MOJI ΝΥΣΤΑΖΕΙ... ΕΠΑΝΑΣΥΝΔΕΣΗ ΣΥΝΔΕΣΜΟΥ ΓΛΩΣΣΑΣ'; mojiSleepHintNight='Ο MOJI ΚΟΙΜΑΤΑΙ... ΠΑΤΗΣΕ ΓΙΑ ΞΥΠΝΗΜΑ'; mojiWakeSuccess='Χασμουρητό... Ο Moji ξύπνησε! Ας εξασκηθούμε!'; mojiSleepReasonReconnect='Ο Moji νυστάζει όσο επανασυνδέεται ο σύνδεσμος γλώσσας.'; mojiSleepReasonNight='Ο Moji κοιμάται. Πάτησε για ξύπνημα.' }
}
function Escape-JsonString([string]$v){ if($null -eq $v){ return '' }; return $v.Replace('\\','\\\\').Replace('"','\\"') }
Get-ChildItem $root -Filter 'app_*.arb' | Where-Object { $_.Name -notlike 'app_localizations*' } | ForEach-Object {
  $locale = $_.BaseName.Substring(4)
  $map = $translations[$locale]
  if($null -eq $map){ $map = $english }
  $raw = Get-Content -Raw -Path $_.FullName
  if($raw -match '"mojiSleepReconnect"'){ return }
  $keys = @('youLabel','mojiSleepReconnect','mojiSleepNight','mojiSleepHintReconnect','mojiSleepHintNight','mojiWakeSuccess','mojiSleepReasonReconnect','mojiSleepReasonNight')
  $lines = @()
  foreach($k in $keys){ $lines += ('    "{0}":  "{1}"' -f $k, (Escape-JsonString([string]$map[$k])) ) }
  $insert = ",`r`n" + ($lines -join ",`r`n") + "`r`n"
  $updated = [regex]::Replace($raw,'\s*}\s*$', $insert + '}')
  Set-Content -Path $_.FullName -Value $updated -Encoding UTF8
}
Write-Output 'ARB updates completed'
